---
- name: Minecraft Server
  block:
    - include_vars: "{{ ansible_distribution }}.yml"

    - name: install package
      tags: packages,workstation-packages
      package:
        name:
          - java-1.8.0-openjdk-headless
          - tmux
        state: latest

    - name: Create minecraft group
      group:
        name: "{{ minecraft_group }}"

    - name: Create minecraft user
      user:
        name: "{{ minecraft_user }}"
        create_home: no
        group: "{{ minecraft_group }}"

    - name: Creates directory
      file:
        path: "{{ minecraft_home }}"
        state: directory
        recurse: yes
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: 0775

    - name: Download Minecraft Server
      get_url:
        url: "https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar"
        dest: "{{ minecraft_home }}/server.jar"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: 0775

    - name: agree to EULA
      copy:
        src: eula.txt
        dest: "{{ minecraft_home }}/eula.txt"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: 0644

    - name: Copy bash script
      copy:
        src: minecraft_server.sh
        dest: "{{ minecraft_home }}/minecraft_server.sh"
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        mode: 0775

    
    - name: Open port 25565/tcp
      firewalld:
        port: 25565/tcp
        permanent: yes
        state: enabled

    - name: Reserve the huge pages
      lineinfile:
        dest: "/etc/sysctl.conf"
        regexp: "^vm.nr_hugepages ="
        line: "vm.nr_hugepages = 2860"


  when:
    - app_minecraft_server is defined
    - app_minecraft_server is true
...